name: You got da style?

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Style
      run: |
        python3.7 -m pip install click docker flask flask_cors pika pycodestyle pylint pymongo redis yapf
        sh .github/workflows/yapf-test.sh integration_tester 
        python3.7 -m pycodestyle --max-line-length=100 --ignore=E125,W503,W504 integration_tester 
        python3.7 -m pylint --disable=R0913,W0221 integration_tester 

